name: "Terraform Plan/Apply Pipeline"

on:
  workflow_dispatch:
    inputs:
      infra_env:
        type: choice
        description: "Select Subscription"
        options:
          - "CEQ-DEVOPS-SANDBOX"

permissions: read-all
env:
  REGION: us-east-1
jobs:
  terraform-plan:
    name: Terraform Scan & Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_WAR_REMIDIATION_SANDBOX_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_WAR_REMIDIATION_SANDBOX_SECRET_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          download_external_modules: true
          file: ./main.tf

      - name: "Setting Environment"
        env:
          INFRA_ENV: ${{ github.event.inputs.infra_env }}
        run: |
          if [ "$INFRA_ENV" == "CEQ-DEVOPS-SANDBOX" ]; then
           echo "project_id=ceq-devops-sandbox" >> $GITHUB_ENV
           echo "ENV=sandbox" >> $GITHUB_ENV
           echo "bucket=ceq-tf-statefile-aws-wafr" >> $GITHUB_ENV
           echo "tfstatefile=aws-kinesis/terraform.tfstate" >> $GITHUB_ENV
           echo "dynamodbtable=aws-wafr-pipeline" >> $GITHUB_ENV
          elif [ "$INFRA_ENV" == "nonprod" ]; then
            echo "project_id=ceq-devops-sandbox" >> $GITHUB_ENV
            echo "ENV=nonprod" >> $GITHUB_ENV
            echo "bucket=aws-wafr-pipeline-tf-state" >> $GITHUB_ENV
            echo "aws-aurora/terraform.tfstate" >> $GITHUB_ENV
            echo "dyanmodbtable=AWS_pricing_module_table" >> $GITHUB_ENV
          else
             echo "environment not supported"
             exit 1
          fi

      - name: Setup git global config
        run: git config --global url."https://oauth2:${{secrets.CEQ_GHREPOSVCUSER_PAT_TOKEN}}@github.com".insteadOf https://github.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.2
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init -reconfigure
          -backend-config="bucket=$bucket"
          -backend-config="key=$tfstatefile"
          -backend-config="dynamodb_table=$dynamodbtable"

      - name: Terraform Plan
        run: terraform plan -var-file="$ENV/terraform.tfvars" -out plan.tfplan -input=false

      - name: Terraform Plan convert JSON Format
        run: terraform show -json plan.tfplan > plan.json

      - name: Upload plan.json to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plan
          path: ${{ github.workspace }}/plan.json

      - name: Download plan.json from artifacts
        uses: actions/download-artifact@v4
        with:
          name: plan
          path: ${{ github.workspace }}/downloaded_plan.json

      - name: Execute Scan Template Script
        run: |
          python ./visionapi.py
        env:
          TOKEN: ${{ secrets.API_TOKEN }}

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: ["terraform-plan"]

    environment:
      name: terraform_apply

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_WAR_REMIDIATION_SANDBOX_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_WAR_REMIDIATION_SANDBOX_SECRET_KEY }}
          aws-region: ${{ env.REGION }}

      - name: "Setting Environment"
        env:
          INFRA_ENV: ${{ github.event.inputs.infra_env }}
        run: |
          if [ "$INFRA_ENV" == "CEQ-DEVOPS-SANDBOX" ]; then
           echo "project_id=ceq-devops-sandbox" >> $GITHUB_ENV
           echo "ENV=sandbox" >> $GITHUB_ENV
           echo "bucket=ceq-tf-statefile-aws-wafr" >> $GITHUB_ENV
           echo "tfstatefile=aws-kinesis/terraform.tfstate" >> $GITHUB_ENV
           echo "dynamodbtable=aws-wafr-pipeline" >> $GITHUB_ENV
          elif [ "$INFRA_ENV" == "nonprod" ]; then
            echo "project_id=ceq-devops-sandbox" >> $GITHUB_ENV
            echo "ENV=nonprod" >> $GITHUB_ENV
            echo "bucket=aws-wafr-pipeline-tf-state" >> $GITHUB_ENV
            echo "aws-aurora/terraform.tfstate" >> $GITHUB_ENV
            echo "dyanmodbtable=AWS_pricing_module_table" >> $GITHUB_ENV
          else
             echo "environment not supported"
             exit 1
          fi

      - name: Setup git global config
        run: git config --global url."https://oauth2:${{secrets.CEQ_GHREPOSVCUSER_PAT_TOKEN}}@github.com".insteadOf https://github.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.2
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init -reconfigure
          -backend-config="bucket=$bucket"
          -backend-config="key=$tfstatefile"
          -backend-config="dynamodb_table=$dynamodbtable"

      - name: Terraform Apply
        run: terraform apply -var-file="$ENV/terraform.tfvars" -auto-approve -input=false
